# Generated by Django 2.2.4 on 2019-11-25 18:01
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dev", "0005_organisation_librarians"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="dev_organisations_where_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
