# Generated by Django 2.2.4 on 2019-11-29 00:11
from django.db import migrations
from django.db import models

import mhep.dev.models.image


class Migration(migrations.Migration):

    dependencies = [("dev", "0007_add_image_model_and_featured_image")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                max_length=200, upload_to=mhep.dev.models.image.Image._image_path
            ),
        )
    ]
