# Generated by Django 2.2.4 on 2019-12-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0008_library_shared_with"),
        ("dev", "0008_remove_image_auto_width_height"),
    ]

    operations = []
