# Generated by Django 2.2.4 on 2019-12-12 13:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import mhep.dev.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_merge_20191202_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[mhep.dev.validators.validate_dict, mhep.dev.validators.validate_report]),
        ),
    ]
