variables:
    # Change pip's cache directory to be inside the project directory since we can
    # only cache local items.
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

stages:
    - docs
    - test

test:
    stage: test
    needs: []
    image: python:3.7-buster
    services:
        - postgres:11
    variables:
        DEBUG: 1
        POSTGRES_DB: mhep
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: trust
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
        DJANGO_SETTINGS_MODULE: config.settings.test

    cache:
        paths:
            - .cache/pip
            - venv

    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install -r requirements/local.txt
    script:
        - pytest --cov=mhep

pages:
    stage: docs
    needs: []
    image: sphinxdoc/sphinx:3.3.0
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
          changes:
          - docs/**/*

    artifacts:
        paths:
            - public

    script:
        - pip install sphinx-rtd-theme
        - make html -C docs/
        - mv docs/_build/html/ public/
