stages:
    - docs
    - test

test:
    stage: test
    needs: []
    image: python:3.7-buster
    services:
        - postgres:11
    variables:
        DEBUG: 1
        POSTGRES_DB: mhep
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: trust
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
        DJANGO_SETTINGS_MODULE: config.settings.test
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

    cache:
        key: test
        paths:
            - ${PIP_CACHE_DIR}
            - venv

    before_script:
        - python -V
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install pip-tools
        - pip-sync requirements/local.txt
    script:
        # Silence warnings
        - mkdir staticfiles
        - pytest --cov=mhep

pre-commit:
    stage: test
    needs: []
    image: python:3.7-buster

    variables:
        PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        key: pre-commit
        when: 'always'
        paths:
            - ${PIP_CACHE_DIR}
            - ${PRE_COMMIT_HOME}

    script:
        - python -V
        - pip install pre-commit==2.8.2
        - pre-commit run --all

pages:
    stage: docs
    needs: []
    image: sphinxdoc/sphinx:3.3.0
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
          changes:
          - docs/**/*

    artifacts:
        paths:
            - public

    script:
        - pip install sphinx-rtd-theme
        - make html -C docs/
        - mv docs/_build/html/ public/
