'!(*.{gif,png,jpg}|*.min.*)':
    - 'prettier --ignore-unknown --write'
    - 'check-merge-conflict'
    - 'scripts/run-lint-hook-without-symlinks fix-byte-order-marker'
    - 'forbid-new-submodules'
    - 'scripts/run-lint-hook-without-symlinks mixed-line-ending --fix=lf'
    - 'scripts/run-lint-hook-without-symlinks trailing-whitespace-fixer'
    - 'scripts/run-lint-hook-without-symlinks end-of-file-fixer'
'client/*.{js,jsx,ts,tsx}': 'eslint --fix'
'*.py':
    - 'black'
    - 'ruff check --fix'
    - 'debug-statement-hook'
    - 'check-docstring-first'
'*.json,!tsconfig.json': 'check-json'
