repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.238
      hooks:
          - id: ruff
            args: ['--fix']

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            types: [file]
            files: \.(ts|tsx|yml|yaml|json|css)$
            additional_dependencies:
                - 'prettier@=2.7.1'
                - 'prettier-plugin-organize-imports@=3.2.2'

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-merge-conflict
          - id: debug-statements
          - id: check-docstring-first
          - id: check-json
            exclude: tsconfig.json
          - id: end-of-file-fixer
            exclude: \.min\.
          - id: fix-byte-order-marker
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: ['--fix=lf']
          - id: trailing-whitespace
