language: python

python:
  - "3.6"

install:
  - pip install -r mhep/requirements/local.txt

services:
    - postgresql

script:
  - cd mhep
  - make test

env:
  global:
    - DATABASE_URL="postgres://postgres:@localhost:5432/travis"

notifications:
    email: false
