# Generated by Django 3.1.7 on 2021-03-30 14:08
from django.db import migrations


def copy_data_forward(apps, schema_editor):
    """Set site domain and name."""
    V2Organisation = apps.get_model("v2", "Organisation")
    GlobalOrganisation = apps.get_model("organisations", "Organisation")
    for old_org in V2Organisation.objects.all():
        new_org, created = GlobalOrganisation.objects.update_or_create(
            id=old_org.id,
            defaults={"name": old_org.name},
        )

        new_org.members.set(list(old_org.members.all()))
        new_org.librarians.set(list(old_org.librarians.all()))
        new_org.admins.set(list(old_org.admins.all()))

        old_org.organisation = new_org
        old_org.save()


def copy_data_backward(apps, schema_editor):
    """Revert site domain and name to default."""
    Organisation = apps.get_model("organisations", "Organisation")
    Organisation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0001_initial"),
        ("v2", "0006_fk_to_global_org"),
    ]

    operations = [migrations.RunPython(copy_data_forward, copy_data_backward)]
