# Generated by Django 4.0.5 on 2023-01-05 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0002_copy_v2_org_data"),
        ("v2", "0011_remove_external_organisation_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Organisation",
        ),
    ]
