# Generated by Django 4.1.5 on 2023-05-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v2", "0011_remove_external_organisation_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Complete", "Complete"),
                    ("In progress", "In progress"),
                    ("For review", "For review"),
                    ("Test", "Test"),
                ],
                default="In progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
