# Generated by Django 4.1.5 on 2023-08-03 15:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import macquette.v2.models.report


class Migration(migrations.Migration):
    dependencies = [
        ("v2", "0012_remove_assessment_updated_at_auto_now"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=200,
                        upload_to=macquette.v2.models.report.Report._report_path,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="v2.assessment",
                    ),
                ),
            ],
        ),
    ]
