# Generated by Django 3.1.7 on 2021-03-16 14:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("v2", "0003_add_shared_assessment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="library",
            name="owner_cant_be_both_user_and_organisation",
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("owner_user__isnull", False),
                        ("owner_organisation__isnull", True),
                    ),
                    models.Q(
                        ("owner_user__isnull", True),
                        ("owner_organisation__isnull", False),
                    ),
                    models.Q(
                        ("owner_user__isnull", True),
                        ("owner_organisation__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="v2_library_owner_cant_be_both_user_and_organisation",
            ),
        ),
    ]
