# Generated by Django 4.0.3 on 2022-05-12 15:58
from django.db import migrations
from django.db import models

import mhep.v2.models.report_template
import mhep.v2.validators


class Migration(migrations.Migration):

    dependencies = [
        ("v2", "0007_new_report_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, validators=[mhep.v2.validators.validate_dict]
            ),
        ),
    ]
