# Generated by Django 4.0.5 on 2023-01-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import mhep.v2.models.report_template
import mhep.v2.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v2", "0009_remove_old_report_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_shared_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_libraries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_organisations_where_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="librarians",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_organisations_where_librarian",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_organisations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="report_vars",
            field=models.JSONField(
                blank=True, default=dict, validators=[mhep.v2.validators.validate_dict]
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="template",
            field=models.TextField(
                validators=[mhep.v2.models.report_template._validate_template]
            ),
        ),
    ]
