# Generated by Django 4.0.5 on 2023-01-05 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v2", "0010_unclear"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="organisation",
        ),
    ]
