version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    image: postgres:11
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    environment:
        POSTGRES_USER: LmYWLIqTOZmyPvoPFgVnwgWCtJrSLjGQ
        POSTGRES_PASSWORD: 4OcGftfvqhATVNtcc2pCtgKgTM73mKawUj2ovVlScwgvf9D38nqLzKEDB81OIbmc
        POSTGRES_DB: hub
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
      - "1025:1025"
