#!/bin/sh

set -eu

# Run lint-staged on entire repository

empty_tree_hash="$(git hash-object -t tree /dev/null)"
export PATH="$(git rev-parse --show-toplevel)/client/node_modules/.bin:$PATH"
lint-staged --diff "$empty_tree_hash" --no-stash

if [ -n "$(git status --porcelain=2)" ]; then
    echo "Repository was modified by hooks" >&2
    exit 1
fi
