#!/usr/bin/env python

from sys import argv
from os.path import islink
from os import execvp

hook = argv[1]
args = [arg for arg in argv[2:] if arg.startswith("--") or not islink(arg)]

execvp(hook, args)
