#!/usr/bin/env node

// Run the model
// Take the input JSON from stdin

'use strict';

const model = require('../mhep/dev/static/dev/js/model.js');
const datasets = require('../mhep/dev/static/dev/js/model-datasets.js');
const util = require('../mhep/dev/static/dev/js/misc.js');

const fs = require('fs');
const buffer = fs.readFileSync(0); // STDIN_FILENO = 0
const assessment = JSON.parse(buffer);

for (let scenario of util.get_scenario_ids(assessment)) {
    assessment[scenario] = model.run(assessment[scenario], datasets);
}

console.log(JSON.stringify(assessment, null, 4));
