# Generated by Django 2.2.4 on 2019-11-29 00:11
import pathlib

from django.db import migrations, models


def _image_path(self, filename):
    extension = pathlib.PurePath(filename).suffix
    return f"images/{self.uuid}{extension}"


class Migration(migrations.Migration):

    dependencies = [("dev", "0007_add_image_model_and_featured_image")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(max_length=200, upload_to=_image_path),
        )
    ]
