# Generated by Django 2.2.4 on 2020-01-24 17:34
import django.contrib.postgres.fields.jsonb
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0011_excise_opembem_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="report_template",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="report",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
